# -*- coding: utf-8 -*-
"""Parameter Tuning (Network Architecture).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CLmRuh8aQnh0pmjppm8HkA1oE8aq3w4i
"""

import numpy as np
import random
from collections import deque
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import AdamW
import gym
import itertools
from matplotlib import pyplot as plt

def argmax(x):
    ''' Own variant of np.argmax with random tie breaking, function of assignment 1  '''
    try:
        return np.random.choice(np.where(x == np.max(x))[0])
    except:
        return np.argmax(x)

def softmax(x, temp):
    ''' Computes the softmax of vector x with temperature parameter 'temp', function of assignment 1 '''
    x = x / temp  # scale by temperature
    z = x - max(x)  # substract max to prevent overflow of softmax
    return np.exp(z) / np.sum(np.exp(z))  # compute softmax

class DQAgent:
    def __init__(self, state_size, action_size, layers=[32, 16], replay_memory_capacity=1000, epsilon=0.5, target=True, replay=True):
        self.state_size = state_size  # Set output size for Q-function
        self.action_size = action_size  # Set input size for Q-function
        self.memory = deque(maxlen=replay_memory_capacity)  # Initialize replay memory to capacity N
        self.gamma = 0.95  # Future rewards are discounted by gamma per time-step
        self.Q_network = self._build_model(layers)  # Initialize action-value function Q with random weights
        self.Q_network_target = self._build_model(layers)
        self.epsilon = epsilon  # Probability for random action
        self.epsilon_min = 0.01
        self.episodes_max = 10
        self.target = target  # If True predictions are made using an alternate network that undergoes periodic updates
        self.use_replay = replay # If True experience replay will be used

    def _build_model(self, layers):  # Takes state as input, outputs Q values for legal actions
        model = Sequential()
        model.add(Dense(layers[0], input_dim=self.state_size, activation='relu'))
        for units in layers[1:]:
            model.add(Dense(units, activation='relu'))
        model.add(Dense(self.action_size, activation='linear'))
        model.compile(loss='mse', optimizer=AdamW(learning_rate=0.1), metrics=['accuracy'])
        return model

    def store_transition(self, s, a, r, s_next, done):  # Stores transition in replay memory
        self.memory.append((s, a, r, s_next, done))

    def Q_value_predict(self, s):
        if self.target:
            return self.Q_network_target.predict(s, verbose=0)
        else:
            return self.Q_network.predict(s, verbose=0)

    def replay(self, batch_size):
        if self.use_replay:
            minibatch = random.sample(self.memory, batch_size)  # if experience replay is used experiences are randomly sampled from memory
        else:
            index = len(self.memory) - batch_size
            minibatch = list(itertools.islice(self.memory, index, None))  # if experience replay is not used the model is trained on the last experiences

        for s, a, r, s_next, done in minibatch:
            if done:
                y = r
            else:
                Q_next = np.amax(self.Q_value_predict(s_next)[0])
                y = r + self.gamma * Q_next
            Q = self.Q_value_predict(s)
            Q[0][a] = y
            self.Q_network.fit(s, Q, verbose=0)  # Keras builds the loss function akin to equation 3 as outlined in the DQN paper.

    def select_action(self, s, current_episode, method="anneal_epsilon"):
        random_action = env.action_space.sample() # Random action
        Q_values = self.Q_network.predict(s, verbose=0)  # Get Q-values from Q-function
        greedy_action = np.argmax(Q_values[0])  # action associated with the maximum Q-value
        if method == "egreedy":
            if self.epsilon >= np.random.rand():
                return random_action
            else:
                return greedy_action
        elif method == "anneal_epsilon":
            self.linear_annealing_epsilon(current_episode)
            if self.epsilon >= np.random.rand():
                return random_action
            else:
                return greedy_action
        elif method == "boltzmann":
            return argmax(softmax(Q_values, self.epsilon))

    def update_target_network(self):
        self.Q_network_target.set_weights(self.Q_network.get_weights())

    def linear_annealing_epsilon(self, current_episode):
        """Linear function decay of epsilon parameter """
        gradient_epsilon = (self.epsilon_min - 1.0) / self.episodes_max
        self.epsilon = gradient_epsilon * current_episode + 1.0

if __name__ == "__main__":
    env = gym.make('CartPole-v1')
    state_size = env.observation_space.shape[0]
    action_size = env.action_space.n
    episodes = 20
    batch_size = 16
    rewards = []

    network_architectures = [
        [32, 16],
        [64, 32],
        [128, 64]
    ]  # Define network architectures to search over

    rewards_per_architecture = {}  # Dictionary to store rewards per network architecture

    exploration_factor = 0.5

    for layers in network_architectures:
        agent = DQAgent(state_size, action_size, replay=False, layers=layers, epsilon=exploration_factor)  # Initialize agent with current network architecture and exploration factor
        episode_rewards = []

        for e in range(episodes):
            s = env.reset()
            s = np.array([s]).reshape([1, state_size])
            done = False
            time = 0
            while not done and time < 500:  # Corrected the condition for episode termination
                a = agent.select_action(s, e, "anneal_epsilon")
                step_result = env.step(a)
                s_next, r, done, _ = step_result[:4]
                s_next = np.reshape(s_next, [1, state_size])
                agent.store_transition(s, a, r, s_next, done)

                if len(agent.memory) >= batch_size:
                    agent.replay(batch_size)

                s = s_next
                time += 1
                if time % 10 == 0 and agent.target:
                    agent.update_target_network()

            episode_rewards.append(time)
            print("Episode:", e+1, "| Reward:", time)

        rewards_per_architecture[str(layers)] = episode_rewards

    # Plotting rewards for each network architecture
    for layers, rewards in rewards_per_architecture.items():
        plt.plot(range(1, episodes + 1), rewards, label=f'Layers: {layers}')

    plt.title("Rewards per Episode for Different Network Architectures")
    plt.xlabel("Episode")
    plt.ylabel("Reward")
    plt.legend()
    plt.grid(True)
    plt.show()

    env.close()